### ISSUE TITLE
Allow avoidance of Pandas dependency

### ISSUE THREAD

**Issue by sanmai-NL** [alan-turing-institute/CleverCSV#101]
Pandas is a large dependency. That‘s incompatible with using CleverCSV as pre-commit hook under CI. I have scanned the source code and this does not take away my intuition that Pandas isn't strictly needed for CleverCSV. Alternatively or additionally, could you transition to [Polars](https://pola-rs.github.io/polars-book/user-guide/installation/#python) instead of Pandas? That has subpackages.

**Comment by GjjvdBurg** [comment]
Thanks for calling this out, it's fixed in v0.8.2. The [pre-commit hook](https://github.com/alan-turing-institute/CleverCSV-pre-commit) has been updated to depend only on the `clevercsv[precommit]` installation target. This target only has the required dependencies needed for the precommit hook ([details](https://github.com/alan-turing-institute/CleverCSV/blob/master/setup.py#L32)), which does not include pandas.

You can update your `.pre-commit-config.yaml` file with `rev: v0.8.2`  to use the update.
